
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
* To change this template, choose Tools | Templates
* and open the template in the editor.
*/

/**
 *
 * @author 499326
 */
public class FrameDisplay extends javax.swing.JFrame {
    
    /**
     * Creates new form FrameDisplay
     */
    
    static String selectedItem = null;//stores selected item's employee number and last name in the format (### - XXX)
    
    public FrameDisplay() {
        initComponents();
        
        //creates default list model consisting of all employees in hashtable
        //adds employee from hashtable to list one by one
        DefaultListModel <String> allEmployees = new DefaultListModel<String>();
        for (int i = 0; i < FrameMain.getEmployeeHashTable().getBuckets().length; i++)
        {
            for (int j = 0; j < FrameMain.getEmployeeHashTable().getBuckets()[i].size(); j++)
            {
                allEmployees.addElement (FrameMain.getEmployeeHashTable().getBuckets()[i].get(j).getEmployeeNumber() + " - " + FrameMain.getEmployeeHashTable().getBuckets()[i].get(j).getLastName().toUpperCase());
            }
        }
        listDisplayAllEmployees.setModel(allEmployees);
        
        //sets initial visibility of panels and error labels
        panelDisplayEmployee.setVisible(false);//display panel invisible
        labelDisplayError.setVisible(false);//error message invisible
        labelDisplayErrorNoEmployee.setVisible(false);//error message invisible
        
        //popup appears if user tries to close window
        addWindowListener(new WindowAdapter()
        {
            @Override
            public void windowClosing(WindowEvent e)
            {
                int selectedOption = JOptionPane.showConfirmDialog(null,
                        "Are you sure you want to close the window?",
                        "EXIT",
                        JOptionPane.YES_NO_OPTION);
                //if user clicks yes, program closes
                if (selectedOption == JOptionPane.YES_OPTION) {
                    e.getWindow().dispose();
                }
            }
        });
    }
    
    //method which returns the string value of sex
    public String getSexString (int sex){
        if (sex == 0){
            return ("Male");
        }
        else if (sex == 1){
            return ("Female");
        }
        else{
            return ("Other");
        }
    }
    
    //method which returns the string value of work location
    public String getWorkLocationString (int workLocation){
        if (workLocation == 0){
            return ("Missisauga");
        }
        else if (workLocation == 1){
            return ("Ottawa");
        }
        else{
            return ("Chicago");
        }
    }
    
    //method which returns employee number of selected item of list
    public static String getSelectedEmployeeNumber (){
        if (selectedItem != null){
            return (FrameMain.getFirstWord(selectedItem));
        }
        else {
            return (null);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDisplayTitle = new javax.swing.JLabel();
        panelDisplayEmployee = new javax.swing.JPanel();
        labelDisplayFirstName = new javax.swing.JLabel();
        labelDisplayLastName = new javax.swing.JLabel();
        labelDisplayEmployeeNumber = new javax.swing.JLabel();
        labelDisplaySex = new javax.swing.JLabel();
        labelDisplayWorkLocation = new javax.swing.JLabel();
        labelDisplayEmployeeType = new javax.swing.JLabel();
        labelDisplayDeductionsRate = new javax.swing.JLabel();
        panelDisplayPartTime = new javax.swing.JPanel();
        labelDisplayHourlyWage = new javax.swing.JLabel();
        labelDisplayHoursPerWeek = new javax.swing.JLabel();
        labelDisplayWeeksPerYear = new javax.swing.JLabel();
        labelDisplayHourlyWageAnswer = new javax.swing.JLabel();
        labelDisplayHoursPerWeekAnswer = new javax.swing.JLabel();
        labelDisplayWeeksPerYearAnswer = new javax.swing.JLabel();
        panelDisplayFullTime = new javax.swing.JPanel();
        labelDisplayAnnualSalary = new javax.swing.JLabel();
        labelDisplayAnnualSalaryAnswer = new javax.swing.JLabel();
        labelDisplayAnnualGrossIncome = new javax.swing.JLabel();
        labelDisplayFirstNameAnswer = new javax.swing.JLabel();
        labelDisplayLastNameAnswer = new javax.swing.JLabel();
        labelDisplayEmployeeNumberAnswer = new javax.swing.JLabel();
        labelDisplaySexAnswer = new javax.swing.JLabel();
        labelDisplayWorkLocationAnswer = new javax.swing.JLabel();
        labelDisplayEmployeeTypeAnswer = new javax.swing.JLabel();
        labelDisplayDeductionsRateAnswer = new javax.swing.JLabel();
        labelDisplayAnnualGrossIncomeAnswer = new javax.swing.JLabel();
        labelDisplayError = new javax.swing.JLabel();
        scrollPanelDisplayAllEmployees = new javax.swing.JScrollPane();
        listDisplayAllEmployees = new javax.swing.JList<>();
        buttonDisplayEdit = new javax.swing.JButton();
        buttonDisplayRemove = new javax.swing.JButton();
        buttonDisplayExit = new javax.swing.JButton();
        buttonDisplaySearch = new javax.swing.JButton();
        labelDisplayErrorNoEmployee = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        labelDisplayTitle.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        labelDisplayTitle.setText("List of Employees");

        panelDisplayEmployee.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelDisplayFirstName.setText("First Name");

        labelDisplayLastName.setText("Last Name");

        labelDisplayEmployeeNumber.setText("Employee Number");

        labelDisplaySex.setText("Sex");

        labelDisplayWorkLocation.setText("Work Location");

        labelDisplayEmployeeType.setText("Employee Type");

        labelDisplayDeductionsRate.setText("Deductions Rate");

        panelDisplayPartTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelDisplayHourlyWage.setText("Hourly Wage");

        labelDisplayHoursPerWeek.setText("Hours Per Week");

        labelDisplayWeeksPerYear.setText("Weeks Per Year");

        labelDisplayHourlyWageAnswer.setText("$XXX.XX");

        labelDisplayHoursPerWeekAnswer.setText("XXX");

        labelDisplayWeeksPerYearAnswer.setText("XX");

        javax.swing.GroupLayout panelDisplayPartTimeLayout = new javax.swing.GroupLayout(panelDisplayPartTime);
        panelDisplayPartTime.setLayout(panelDisplayPartTimeLayout);
        panelDisplayPartTimeLayout.setHorizontalGroup(
            panelDisplayPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDisplayPartTimeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDisplayPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDisplayHourlyWage)
                    .addComponent(labelDisplayHoursPerWeek)
                    .addComponent(labelDisplayWeeksPerYear)
                    .addComponent(labelDisplayHourlyWageAnswer)
                    .addComponent(labelDisplayHoursPerWeekAnswer)
                    .addComponent(labelDisplayWeeksPerYearAnswer))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        panelDisplayPartTimeLayout.setVerticalGroup(
            panelDisplayPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDisplayPartTimeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDisplayHourlyWage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDisplayHourlyWageAnswer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDisplayHoursPerWeek)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDisplayHoursPerWeekAnswer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDisplayWeeksPerYear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDisplayWeeksPerYearAnswer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDisplayFullTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelDisplayAnnualSalary.setText("Annual Salary");

        labelDisplayAnnualSalaryAnswer.setText("$XXXXX.XX");

        javax.swing.GroupLayout panelDisplayFullTimeLayout = new javax.swing.GroupLayout(panelDisplayFullTime);
        panelDisplayFullTime.setLayout(panelDisplayFullTimeLayout);
        panelDisplayFullTimeLayout.setHorizontalGroup(
            panelDisplayFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDisplayFullTimeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDisplayFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDisplayAnnualSalary)
                    .addComponent(labelDisplayAnnualSalaryAnswer))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        panelDisplayFullTimeLayout.setVerticalGroup(
            panelDisplayFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDisplayFullTimeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDisplayAnnualSalary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDisplayAnnualSalaryAnswer)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        labelDisplayAnnualGrossIncome.setText("Annual Gross Income");

        labelDisplayFirstNameAnswer.setText("XXXXXXXXXX");

        labelDisplayLastNameAnswer.setText("XXXXXXXXXXX");

        labelDisplayEmployeeNumberAnswer.setText("#####");

        labelDisplaySexAnswer.setText("Female");

        labelDisplayWorkLocationAnswer.setText("Mississauga");

        labelDisplayEmployeeTypeAnswer.setText("Full Time");

        labelDisplayDeductionsRateAnswer.setText("0.0005");

        labelDisplayAnnualGrossIncomeAnswer.setText("$XXX.XX");

        labelDisplayError.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        labelDisplayError.setForeground(new java.awt.Color(255, 0, 0));
        labelDisplayError.setText("ERROR: Employee not found.");

        javax.swing.GroupLayout panelDisplayEmployeeLayout = new javax.swing.GroupLayout(panelDisplayEmployee);
        panelDisplayEmployee.setLayout(panelDisplayEmployeeLayout);
        panelDisplayEmployeeLayout.setHorizontalGroup(
            panelDisplayEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDisplayEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDisplayEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDisplayEmployeeLayout.createSequentialGroup()
                        .addComponent(labelDisplayAnnualGrossIncome)
                        .addGap(18, 18, 18)
                        .addComponent(labelDisplayAnnualGrossIncomeAnswer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelDisplayError))
                    .addGroup(panelDisplayEmployeeLayout.createSequentialGroup()
                        .addGroup(panelDisplayEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDisplayEmployeeLayout.createSequentialGroup()
                                .addGroup(panelDisplayEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDisplaySex)
                                    .addGroup(panelDisplayEmployeeLayout.createSequentialGroup()
                                        .addGroup(panelDisplayEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelDisplayFirstName)
                                            .addComponent(labelDisplayFirstNameAnswer))
                                        .addGap(52, 52, 52)
                                        .addGroup(panelDisplayEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelDisplayLastName)
                                            .addComponent(labelDisplayLastNameAnswer))))
                                .addGap(60, 60, 60)
                                .addGroup(panelDisplayEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDisplayEmployeeNumberAnswer)
                                    .addComponent(labelDisplayEmployeeNumber)))
                            .addGroup(panelDisplayEmployeeLayout.createSequentialGroup()
                                .addComponent(panelDisplayPartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelDisplayFullTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDisplayEmployeeLayout.createSequentialGroup()
                                .addComponent(labelDisplaySexAnswer)
                                .addGap(18, 18, 18)
                                .addGroup(panelDisplayEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDisplayWorkLocation)
                                    .addComponent(labelDisplayWorkLocationAnswer))
                                .addGap(18, 18, 18)
                                .addGroup(panelDisplayEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDisplayEmployeeType)
                                    .addComponent(labelDisplayEmployeeTypeAnswer))
                                .addGap(18, 18, 18)
                                .addGroup(panelDisplayEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDisplayDeductionsRateAnswer)
                                    .addComponent(labelDisplayDeductionsRate))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDisplayEmployeeLayout.setVerticalGroup(
            panelDisplayEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDisplayEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDisplayEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDisplayFirstName)
                    .addComponent(labelDisplayLastName)
                    .addComponent(labelDisplayEmployeeNumber))
                .addGroup(panelDisplayEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDisplayEmployeeLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(panelDisplayEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelDisplayFirstNameAnswer)
                            .addComponent(labelDisplayEmployeeNumberAnswer)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDisplayEmployeeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDisplayLastNameAnswer)))
                .addGap(18, 18, 18)
                .addGroup(panelDisplayEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDisplayDeductionsRate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDisplayEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelDisplaySex)
                        .addComponent(labelDisplayWorkLocation)
                        .addComponent(labelDisplayEmployeeType)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDisplayEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelDisplayDeductionsRateAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelDisplayEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelDisplaySexAnswer)
                        .addComponent(labelDisplayWorkLocationAnswer)
                        .addComponent(labelDisplayEmployeeTypeAnswer)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDisplayEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDisplayPartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDisplayFullTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelDisplayEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDisplayAnnualGrossIncome)
                    .addComponent(labelDisplayAnnualGrossIncomeAnswer)
                    .addComponent(labelDisplayError))
                .addContainerGap())
        );

        listDisplayAllEmployees.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        listDisplayAllEmployees.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        listDisplayAllEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listDisplayAllEmployeesMouseClicked(evt);
            }
        });
        scrollPanelDisplayAllEmployees.setViewportView(listDisplayAllEmployees);

        buttonDisplayEdit.setText("Edit");
        buttonDisplayEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDisplayEditActionPerformed(evt);
            }
        });

        buttonDisplayRemove.setText("Remove");
        buttonDisplayRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDisplayRemoveActionPerformed(evt);
            }
        });

        buttonDisplayExit.setText("Exit");
        buttonDisplayExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDisplayExitActionPerformed(evt);
            }
        });

        buttonDisplaySearch.setText("Search");
        buttonDisplaySearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDisplaySearchActionPerformed(evt);
            }
        });

        labelDisplayErrorNoEmployee.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        labelDisplayErrorNoEmployee.setForeground(new java.awt.Color(255, 0, 0));
        labelDisplayErrorNoEmployee.setText("ERROR: No employee selected.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPanelDisplayAllEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panelDisplayEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonDisplaySearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonDisplayEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonDisplayRemove)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonDisplayExit)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelDisplayErrorNoEmployee)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelDisplayTitle)
                .addGap(154, 154, 154))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDisplayTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelDisplayEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelDisplayErrorNoEmployee)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonDisplayExit)
                            .addComponent(buttonDisplayRemove)
                            .addComponent(buttonDisplayEdit)
                            .addComponent(buttonDisplaySearch)))
                    .addComponent(scrollPanelDisplayAllEmployees))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void listDisplayAllEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listDisplayAllEmployeesMouseClicked
        //When user clicks an item on the list, the corresponding information is displayed
        selectedItem = (String)listDisplayAllEmployees.getSelectedValue();
        //finds item clicked by user in hash tabel and displays it's contents
        selectedItem = FrameMain.getFirstWord(selectedItem); //updates selected item to employee number only
        
        //searches for employee in hash table and then displays employee info
        //stores bucket and position in list of employee in variables "currentBucket" and "position"
        int currentBucket = FrameMain.getEmployeeHashTable().calcBucket(Integer.parseInt(FrameMain.getFirstWord(selectedItem)));
        int position = FrameMain.getEmployeeHashTable().searchEmployee(Integer.parseInt(FrameMain.getFirstWord(selectedItem)));
        EmployeeInfo currentEmployee = FrameMain.getEmployeeHashTable().getBuckets()[currentBucket].get(position);//stores the employee of interest
        
        //displays information of employee
        labelDisplayEmployeeNumberAnswer.setText(String.valueOf(currentEmployee.getEmployeeNumber()));
        labelDisplayFirstNameAnswer.setText(currentEmployee.getFirstName());
        labelDisplayLastNameAnswer.setText(currentEmployee.getLastName());
        labelDisplaySexAnswer.setText(getSexString(currentEmployee.getSex()));
        labelDisplayWorkLocationAnswer.setText(getWorkLocationString(currentEmployee.getWorkLocation()));
        labelDisplayDeductionsRateAnswer.setText(String.format("%.2f",currentEmployee.getDeductionsRate()));
        
        //if the employee is part time
        if (currentEmployee instanceof PartTimeEmployee) {
            labelDisplayEmployeeTypeAnswer.setText("Part Time");
            labelDisplayHourlyWageAnswer.setText(String.format("%.2f",((PartTimeEmployee)currentEmployee).getHourlyWage()));
            labelDisplayHoursPerWeekAnswer.setText(String.format("%.2f",((PartTimeEmployee)currentEmployee).getHoursPerWeek()));
            labelDisplayWeeksPerYearAnswer.setText(String.format("%.2f",((PartTimeEmployee)currentEmployee).getWeeksPerYear()));
            labelDisplayAnnualGrossIncomeAnswer.setText(String.format("%.2f",((PartTimeEmployee)currentEmployee).calcAnnualGrossIncome()));
            panelDisplayFullTime.setVisible(false);
            panelDisplayPartTime.setVisible(true);
            labelDisplayError.setVisible(false);
        }
        //if the employee is full time
        else if (currentEmployee instanceof FullTimeEmployee) {
            labelDisplayEmployeeTypeAnswer.setText("Full Time");
            labelDisplayAnnualSalaryAnswer.setText(String.format("%.2f",((FullTimeEmployee)currentEmployee).getAnnualSalary()));
            labelDisplayAnnualGrossIncomeAnswer.setText(String.format("%.2f",((FullTimeEmployee)currentEmployee).calcAnnualGrossIncome()));
            panelDisplayFullTime.setVisible(true);
            panelDisplayPartTime.setVisible(false);
            labelDisplayError.setVisible(false);
        }
        //there is an error; employee is neither part time or fulltime
        else {
            labelDisplayError.setText("ERROR: Employee does not exist.");
            labelDisplayError.setVisible(true);
        }
        //sets visibility of panels
        panelDisplayEmployee.setVisible(true);//employee information is visible
        labelDisplayErrorNoEmployee.setVisible(false);//there is an employee selected
    }//GEN-LAST:event_listDisplayAllEmployeesMouseClicked
    
    private void buttonDisplayExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDisplayExitActionPerformed
        //closes display frame and returns to main menu
        dispose();
        new FrameMain().setVisible(true);
    }//GEN-LAST:event_buttonDisplayExitActionPerformed
    
    private void buttonDisplayEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDisplayEditActionPerformed
        if (selectedItem != null){//if an item is selected
            // closes display frame and opens edit frame
            dispose();
            new FrameEdit().setVisible(true);
            labelDisplayErrorNoEmployee.setVisible(false);
        }
        else {
            //error, no employee selected
            labelDisplayErrorNoEmployee.setVisible(true);
        }
    }//GEN-LAST:event_buttonDisplayEditActionPerformed
    
    private void buttonDisplayRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDisplayRemoveActionPerformed
        if (selectedItem != null){//if an item is selected
            // closes display frame and opens remove frame
            dispose();
            new FrameRemove().setVisible(true);
            labelDisplayErrorNoEmployee.setVisible(false);
        }
        else {
            //error, no employee selected
            labelDisplayErrorNoEmployee.setVisible(true);
        }
    }//GEN-LAST:event_buttonDisplayRemoveActionPerformed
    
    private void buttonDisplaySearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDisplaySearchActionPerformed
        // closes display frame and opens search frame
        dispose();
        new FrameSearch().setVisible(true);
    }//GEN-LAST:event_buttonDisplaySearchActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameDisplay().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonDisplayEdit;
    private javax.swing.JButton buttonDisplayExit;
    private javax.swing.JButton buttonDisplayRemove;
    private javax.swing.JButton buttonDisplaySearch;
    private javax.swing.JLabel labelDisplayAnnualGrossIncome;
    private javax.swing.JLabel labelDisplayAnnualGrossIncomeAnswer;
    private javax.swing.JLabel labelDisplayAnnualSalary;
    private javax.swing.JLabel labelDisplayAnnualSalaryAnswer;
    private javax.swing.JLabel labelDisplayDeductionsRate;
    private javax.swing.JLabel labelDisplayDeductionsRateAnswer;
    private javax.swing.JLabel labelDisplayEmployeeNumber;
    private javax.swing.JLabel labelDisplayEmployeeNumberAnswer;
    private javax.swing.JLabel labelDisplayEmployeeType;
    private javax.swing.JLabel labelDisplayEmployeeTypeAnswer;
    private javax.swing.JLabel labelDisplayError;
    private javax.swing.JLabel labelDisplayErrorNoEmployee;
    private javax.swing.JLabel labelDisplayFirstName;
    private javax.swing.JLabel labelDisplayFirstNameAnswer;
    private javax.swing.JLabel labelDisplayHourlyWage;
    private javax.swing.JLabel labelDisplayHourlyWageAnswer;
    private javax.swing.JLabel labelDisplayHoursPerWeek;
    private javax.swing.JLabel labelDisplayHoursPerWeekAnswer;
    private javax.swing.JLabel labelDisplayLastName;
    private javax.swing.JLabel labelDisplayLastNameAnswer;
    private javax.swing.JLabel labelDisplaySex;
    private javax.swing.JLabel labelDisplaySexAnswer;
    private javax.swing.JLabel labelDisplayTitle;
    private javax.swing.JLabel labelDisplayWeeksPerYear;
    private javax.swing.JLabel labelDisplayWeeksPerYearAnswer;
    private javax.swing.JLabel labelDisplayWorkLocation;
    private javax.swing.JLabel labelDisplayWorkLocationAnswer;
    private javax.swing.JList<String> listDisplayAllEmployees;
    private javax.swing.JPanel panelDisplayEmployee;
    private javax.swing.JPanel panelDisplayFullTime;
    private javax.swing.JPanel panelDisplayPartTime;
    private javax.swing.JScrollPane scrollPanelDisplayAllEmployees;
    // End of variables declaration//GEN-END:variables
}
