
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;


/*
* To change this template, choose Tools | Templates
* and open the template in the editor.
*/

/**
 *
 * @author 499326
 */
public class FrameAdd extends javax.swing.JFrame {
    
    
    /**
     * Creates new form FrameAdd
     */
    public FrameAdd() {
        initComponents();
        //sets initial visibilities of frames
        panelAddPartTime.setVisible(false);
        panelAddFullTime.setVisible(false);
        panelAddMessage.setVisible(false);
        
        //popup appears if user tries to close window
        addWindowListener(new WindowAdapter()
        {
            @Override
            public void windowClosing(WindowEvent e)
            {
                int selectedOption = JOptionPane.showConfirmDialog(null,
                        "Are you sure you want to close the window?",
                        "EXIT",
                        JOptionPane.YES_NO_OPTION);
                //if user clicks yes, program closes
                if (selectedOption == JOptionPane.YES_OPTION) {
                    e.getWindow().dispose();
                }
            }
        });
    }
    
    //initializing variables
    private int employeeType = -1; //0 = employee is part time, 1 = full time, -1 = unknown
    private String firstName;
    private String lastName;
    private int employeeNumber;
    private int sex = -1; // 0 - male, 1- female, 2-other
    private int workLocation = -1;// 0 - mississauga, 1- ottawa, 2-chicago
    private double deductionsRate;
    private double hourlyWage;
    private double hoursPerWeek;
    private double weeksPerYear;
    private double annualSalary;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSex = new javax.swing.ButtonGroup();
        buttonGroupWorkLocation = new javax.swing.ButtonGroup();
        buttonGroupEmployeeType = new javax.swing.ButtonGroup();
        labelAddTitle = new javax.swing.JLabel();
        textFieldAddFirstName = new javax.swing.JTextField();
        labelAddFirstName = new javax.swing.JLabel();
        textFieldAddLastName = new javax.swing.JTextField();
        labelAddLastName = new javax.swing.JLabel();
        textFieldAddEmployeeNumber = new javax.swing.JTextField();
        labelAddEmployeeNumber = new javax.swing.JLabel();
        radioAddSexFemale = new javax.swing.JRadioButton();
        radioAddSexMale = new javax.swing.JRadioButton();
        radioAddSexOther = new javax.swing.JRadioButton();
        labelAddSex = new javax.swing.JLabel();
        radioAddWorkLocationMississauga = new javax.swing.JRadioButton();
        radioAddWorkLocationOttawa = new javax.swing.JRadioButton();
        radioAddWorkLocationChicago = new javax.swing.JRadioButton();
        labelAddWorkLocation = new javax.swing.JLabel();
        radioAddPartTime = new javax.swing.JRadioButton();
        radioAddFullTime = new javax.swing.JRadioButton();
        labelAddEmployeeType = new javax.swing.JLabel();
        textFieldAddDeductionsRate = new javax.swing.JTextField();
        labelAddDeductionsRate = new javax.swing.JLabel();
        panelAddPartTime = new javax.swing.JPanel();
        labelAddPartTime = new javax.swing.JLabel();
        textFieldAddHourlyWage = new javax.swing.JTextField();
        labelAddHourlyWage = new javax.swing.JLabel();
        textFieldAddHoursPerWeek = new javax.swing.JTextField();
        labelAddHoursPerWeek = new javax.swing.JLabel();
        textFieldAddWeeksPerYear = new javax.swing.JTextField();
        labelAddWeeksPerYear = new javax.swing.JLabel();
        panelAddFullTime = new javax.swing.JPanel();
        labelAddFullTime = new javax.swing.JLabel();
        textFieldAddAnnualSalary = new javax.swing.JTextField();
        labelAddAnnualSalary = new javax.swing.JLabel();
        buttonAddSave = new javax.swing.JButton();
        buttonAddExit = new javax.swing.JButton();
        panelAddMessage = new javax.swing.JPanel();
        labelAddMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        labelAddTitle.setFont(new java.awt.Font("Microsoft YaHei", 1, 18)); // NOI18N
        labelAddTitle.setText("Add an Employee");

        textFieldAddFirstName.setText("First Name");

        labelAddFirstName.setText("First Name");

        textFieldAddLastName.setText("Last Name");

        labelAddLastName.setText("Last Name");

        textFieldAddEmployeeNumber.setText("Employee Number");

        labelAddEmployeeNumber.setText("Employee Number");

        buttonGroupSex.add(radioAddSexFemale);
        radioAddSexFemale.setText("Female");
        radioAddSexFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAddSexFemaleActionPerformed(evt);
            }
        });

        buttonGroupSex.add(radioAddSexMale);
        radioAddSexMale.setText("Male");
        radioAddSexMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAddSexMaleActionPerformed(evt);
            }
        });

        buttonGroupSex.add(radioAddSexOther);
        radioAddSexOther.setText("Other");
        radioAddSexOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAddSexOtherActionPerformed(evt);
            }
        });

        labelAddSex.setText("Sex");

        buttonGroupWorkLocation.add(radioAddWorkLocationMississauga);
        radioAddWorkLocationMississauga.setText("Mississauga");
        radioAddWorkLocationMississauga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAddWorkLocationMississaugaActionPerformed(evt);
            }
        });

        buttonGroupWorkLocation.add(radioAddWorkLocationOttawa);
        radioAddWorkLocationOttawa.setText("Ottawa");
        radioAddWorkLocationOttawa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAddWorkLocationOttawaActionPerformed(evt);
            }
        });

        buttonGroupWorkLocation.add(radioAddWorkLocationChicago);
        radioAddWorkLocationChicago.setText("Chicago");
        radioAddWorkLocationChicago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAddWorkLocationChicagoActionPerformed(evt);
            }
        });

        labelAddWorkLocation.setText("Work Location");

        buttonGroupEmployeeType.add(radioAddPartTime);
        radioAddPartTime.setText("Part Time Employee");
        radioAddPartTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAddPartTimeActionPerformed(evt);
            }
        });

        buttonGroupEmployeeType.add(radioAddFullTime);
        radioAddFullTime.setText("Full Time Employee");
        radioAddFullTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioAddFullTimeActionPerformed(evt);
            }
        });

        labelAddEmployeeType.setText("Employee Type");

        textFieldAddDeductionsRate.setText("#.##");

        labelAddDeductionsRate.setText("Deductions Rate");

        panelAddPartTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelAddPartTime.setText("Part Time Employee Info");

        textFieldAddHourlyWage.setText("##.##");

        labelAddHourlyWage.setText("Hourly Wage ($)");

        textFieldAddHoursPerWeek.setText("##");

        labelAddHoursPerWeek.setText("Hours Per Week");

        textFieldAddWeeksPerYear.setText("##");

        labelAddWeeksPerYear.setText("Weeks Per Year");

        javax.swing.GroupLayout panelAddPartTimeLayout = new javax.swing.GroupLayout(panelAddPartTime);
        panelAddPartTime.setLayout(panelAddPartTimeLayout);
        panelAddPartTimeLayout.setHorizontalGroup(
            panelAddPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddPartTimeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddPartTimeLayout.createSequentialGroup()
                        .addGroup(panelAddPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAddHourlyWage)
                            .addGroup(panelAddPartTimeLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(textFieldAddHourlyWage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addGroup(panelAddPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAddHoursPerWeek)
                            .addComponent(textFieldAddHoursPerWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelAddPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAddWeeksPerYear)
                            .addComponent(textFieldAddWeeksPerYear, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(labelAddPartTime))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelAddPartTimeLayout.setVerticalGroup(
            panelAddPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddPartTimeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAddPartTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAddHourlyWage)
                    .addComponent(labelAddHoursPerWeek)
                    .addComponent(labelAddWeeksPerYear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddPartTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldAddHoursPerWeek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldAddHourlyWage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldAddWeeksPerYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        panelAddFullTime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelAddFullTime.setText("Full Time Employee Info");

        textFieldAddAnnualSalary.setText("#.##");

        labelAddAnnualSalary.setText("Annual Salary");

        javax.swing.GroupLayout panelAddFullTimeLayout = new javax.swing.GroupLayout(panelAddFullTime);
        panelAddFullTime.setLayout(panelAddFullTimeLayout);
        panelAddFullTimeLayout.setHorizontalGroup(
            panelAddFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddFullTimeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAddFullTime)
                    .addComponent(labelAddAnnualSalary)
                    .addComponent(textFieldAddAnnualSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAddFullTimeLayout.setVerticalGroup(
            panelAddFullTimeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddFullTimeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAddFullTime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelAddAnnualSalary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldAddAnnualSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        buttonAddSave.setText("Save and Exit");
        buttonAddSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddSaveActionPerformed(evt);
            }
        });

        buttonAddExit.setText("Exit");
        buttonAddExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddExitActionPerformed(evt);
            }
        });

        panelAddMessage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelAddMessage.setText("Error: Invalid input(s).");

        javax.swing.GroupLayout panelAddMessageLayout = new javax.swing.GroupLayout(panelAddMessage);
        panelAddMessage.setLayout(panelAddMessageLayout);
        panelAddMessageLayout.setHorizontalGroup(
            panelAddMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddMessageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAddMessage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelAddMessageLayout.setVerticalGroup(
            panelAddMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddMessageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAddMessage)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(labelAddTitle)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldAddFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelAddFirstName))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textFieldAddLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelAddLastName))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelAddEmployeeNumber)
                                    .addComponent(textFieldAddEmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioAddSexFemale)
                                    .addComponent(radioAddSexOther)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(labelAddSex))
                                    .addComponent(radioAddSexMale))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(radioAddWorkLocationMississauga)
                                            .addComponent(labelAddWorkLocation)
                                            .addComponent(radioAddWorkLocationOttawa))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(labelAddEmployeeType)
                                                    .addComponent(radioAddPartTime))
                                                .addGap(14, 14, 14))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(radioAddFullTime)
                                                .addGap(18, 18, 18)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(textFieldAddDeductionsRate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(labelAddDeductionsRate)))
                                    .addComponent(radioAddWorkLocationChicago)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelAddPartTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelAddMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(buttonAddSave)
                                .addGap(10, 10, 10)
                                .addComponent(buttonAddExit))
                            .addComponent(panelAddFullTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelAddTitle)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAddLastName)
                    .addComponent(labelAddEmployeeNumber)
                    .addComponent(labelAddFirstName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldAddFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldAddLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldAddEmployeeNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAddWorkLocation)
                    .addComponent(labelAddSex)
                    .addComponent(labelAddEmployeeType)
                    .addComponent(labelAddDeductionsRate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAddSexFemale)
                    .addComponent(radioAddWorkLocationMississauga)
                    .addComponent(radioAddPartTime)
                    .addComponent(textFieldAddDeductionsRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAddSexMale)
                    .addComponent(radioAddWorkLocationOttawa)
                    .addComponent(radioAddFullTime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioAddSexOther)
                    .addComponent(radioAddWorkLocationChicago))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelAddPartTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(panelAddMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelAddFullTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonAddExit)
                            .addComponent(buttonAddSave))))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void radioAddPartTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAddPartTimeActionPerformed
        //if user selects part time
        //sets visibility of part time panel true and full time false
        panelAddFullTime.setVisible(false);
        panelAddPartTime.setVisible(true);
        employeeType = 0;
    }//GEN-LAST:event_radioAddPartTimeActionPerformed
    
    private void radioAddFullTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAddFullTimeActionPerformed
        //if user selects full time
        //sets visibility of full time panel true and part time false
        panelAddPartTime.setVisible(false);
        panelAddFullTime.setVisible(true);
        employeeType = 1;
    }//GEN-LAST:event_radioAddFullTimeActionPerformed
    
    private void radioAddSexFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAddSexFemaleActionPerformed
        //if sex is female
        sex = 1;
    }//GEN-LAST:event_radioAddSexFemaleActionPerformed
    
    private void radioAddSexMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAddSexMaleActionPerformed
        //if sex is male
        sex = 0;
    }//GEN-LAST:event_radioAddSexMaleActionPerformed
    
    private void radioAddSexOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAddSexOtherActionPerformed
        //if sex is other
        sex = 2;
    }//GEN-LAST:event_radioAddSexOtherActionPerformed
    
    private void radioAddWorkLocationMississaugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAddWorkLocationMississaugaActionPerformed
        //if work location is missisauga
        workLocation = 0;
    }//GEN-LAST:event_radioAddWorkLocationMississaugaActionPerformed
    
    private void radioAddWorkLocationOttawaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAddWorkLocationOttawaActionPerformed
        //if work location is ottawa
        workLocation = 1;
    }//GEN-LAST:event_radioAddWorkLocationOttawaActionPerformed
    
    private void radioAddWorkLocationChicagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioAddWorkLocationChicagoActionPerformed
        //if work location is chicago
        workLocation = 2;
    }//GEN-LAST:event_radioAddWorkLocationChicagoActionPerformed
    
    private void buttonAddSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddSaveActionPerformed
        //puts information from textfields into variables while error checking
        int error = 0;// 0 if no error, 1+ if there is an error
        
        if (textFieldAddFirstName.getText() != null && textFieldAddLastName.getText() != null){
            firstName = textFieldAddFirstName.getText();
            lastName = textFieldAddLastName.getText();
        }
        else {//first name or last name input is null
            error++;
        }
        if (FrameMain.isInteger(textFieldAddEmployeeNumber.getText()) == true && textFieldAddEmployeeNumber.getText() != null){
            employeeNumber = Integer.parseInt(textFieldAddEmployeeNumber.getText());
        }
        else {//employee number input is not an integer
            error++;
        }
        if (FrameMain.isDouble(textFieldAddDeductionsRate.getText())==true && textFieldAddDeductionsRate.getText() != null && (Double.parseDouble(textFieldAddDeductionsRate.getText()) >= 0) && (Double.parseDouble(textFieldAddDeductionsRate.getText())<= 1)){
            deductionsRate = Double.parseDouble(textFieldAddDeductionsRate.getText());
        }
        else{//employee deductions rate is not a real number, nonexistent, or is not within the range between 0-1
            error++;
        }
        
        if (sex == -1 || workLocation == -1){//no input for sex or work location
            error++;
        }
        
        //If there is no error, Add frame will close after saving the data into the tree
        if (employeeType == 0) {//part time
            if (FrameMain.isDouble(textFieldAddHourlyWage.getText())== true
                    && FrameMain.isDouble(textFieldAddHoursPerWeek.getText()) == true
                    && FrameMain.isDouble(textFieldAddWeeksPerYear.getText()) == true
                    && textFieldAddHourlyWage.getText() != null
                    && textFieldAddHoursPerWeek.getText() != null
                    && textFieldAddWeeksPerYear.getText() != null
                    && (Double.parseDouble(textFieldAddHourlyWage.getText()) >= 0)
                    && (Double.parseDouble(textFieldAddHoursPerWeek.getText()) >= 0)
                    && (Double.parseDouble(textFieldAddWeeksPerYear.getText()) >= 0)
                    ){
                hourlyWage = FrameMain.roundTwoDecimals(Double.parseDouble(textFieldAddHourlyWage.getText()));
                hoursPerWeek = FrameMain.roundTwoDecimals(Double.parseDouble(textFieldAddHoursPerWeek.getText()));
                weeksPerYear = FrameMain.roundTwoDecimals(Double.parseDouble(textFieldAddWeeksPerYear.getText()));
            }
            else {// one of the inputs of hourly wage, hours per week and weeks per year is NOT a real value or is empty or is negative
                error++;
            }
            
            //makes employee, closes add frame and opens main frame if there is no error
            if (error == 0){//there is no error
                PartTimeEmployee newPartTimeEmployee = new PartTimeEmployee (employeeNumber, firstName, lastName, sex, workLocation, deductionsRate, hourlyWage, hoursPerWeek, weeksPerYear);
                FrameMain.getEmployeeHashTable().addEmployee(newPartTimeEmployee);
                dispose();
                new FrameMain().setVisible(true);}
            else {//there is an error
                panelAddMessage.setVisible(true);
            }
        }
        else if (employeeType == 1) {//full time
            if (FrameMain.isDouble(textFieldAddAnnualSalary.getText()) == true
                    && textFieldAddAnnualSalary.getText() != null
                    && Double.parseDouble(textFieldAddAnnualSalary.getText()) >= 0
                    ){
                annualSalary = FrameMain.roundTwoDecimals(Double.parseDouble(textFieldAddAnnualSalary.getText()));
            }
            else {//input for annualSalary is not a real value, is empty, or is less than 0, error message is displayed
                panelAddMessage.setVisible(true);
                error++;
            }
            //makes employee, closes add frame and opens main frame if there is no error
            if (error == 0){//there is no error
                FullTimeEmployee newFullTimeEmployee = new FullTimeEmployee (employeeNumber, firstName, lastName, sex, workLocation, deductionsRate, annualSalary);
                FrameMain.getEmployeeHashTable().addEmployee(newFullTimeEmployee);
                dispose();
                new FrameMain().setVisible(true);}
            else {//there is an error
                panelAddMessage.setVisible(true);
            }
            
        }
        else {//undeclared, error message displayed
            panelAddMessage.setVisible(true);
            error++;
        }
        
    }//GEN-LAST:event_buttonAddSaveActionPerformed
    
    private void buttonAddExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddExitActionPerformed
        //closes add frame without saving
        dispose();
        new FrameMain().setVisible(true);
        
    }//GEN-LAST:event_buttonAddExitActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameAdd().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddExit;
    private javax.swing.JButton buttonAddSave;
    private javax.swing.ButtonGroup buttonGroupEmployeeType;
    private javax.swing.ButtonGroup buttonGroupSex;
    private javax.swing.ButtonGroup buttonGroupWorkLocation;
    private javax.swing.JLabel labelAddAnnualSalary;
    private javax.swing.JLabel labelAddDeductionsRate;
    private javax.swing.JLabel labelAddEmployeeNumber;
    private javax.swing.JLabel labelAddEmployeeType;
    private javax.swing.JLabel labelAddFirstName;
    private javax.swing.JLabel labelAddFullTime;
    private javax.swing.JLabel labelAddHourlyWage;
    private javax.swing.JLabel labelAddHoursPerWeek;
    private javax.swing.JLabel labelAddLastName;
    private javax.swing.JLabel labelAddMessage;
    private javax.swing.JLabel labelAddPartTime;
    private javax.swing.JLabel labelAddSex;
    private javax.swing.JLabel labelAddTitle;
    private javax.swing.JLabel labelAddWeeksPerYear;
    private javax.swing.JLabel labelAddWorkLocation;
    private javax.swing.JPanel panelAddFullTime;
    private javax.swing.JPanel panelAddMessage;
    private javax.swing.JPanel panelAddPartTime;
    private javax.swing.JRadioButton radioAddFullTime;
    private javax.swing.JRadioButton radioAddPartTime;
    private javax.swing.JRadioButton radioAddSexFemale;
    private javax.swing.JRadioButton radioAddSexMale;
    private javax.swing.JRadioButton radioAddSexOther;
    private javax.swing.JRadioButton radioAddWorkLocationChicago;
    private javax.swing.JRadioButton radioAddWorkLocationMississauga;
    private javax.swing.JRadioButton radioAddWorkLocationOttawa;
    private javax.swing.JTextField textFieldAddAnnualSalary;
    private javax.swing.JTextField textFieldAddDeductionsRate;
    private javax.swing.JTextField textFieldAddEmployeeNumber;
    private javax.swing.JTextField textFieldAddFirstName;
    private javax.swing.JTextField textFieldAddHourlyWage;
    private javax.swing.JTextField textFieldAddHoursPerWeek;
    private javax.swing.JTextField textFieldAddLastName;
    private javax.swing.JTextField textFieldAddWeeksPerYear;
    // End of variables declaration//GEN-END:variables
}
